#端口
server:
  port: 8888
spring:
  #多数据源配置
  datasource:
    test1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.121.198:3306/newerp2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: devuser
      password: 12345
    test2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/my_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
  #页面配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: html5
    servlet:
      content-type: text/html
#mybatis配置
#mybatis:
  #mapper-locations: classpath:mapper/*/*.xml
  #type-aliases-package: com.neo.model
  #config-locations: classpath:mapper/mybatis-config.xml
#showSql
logging:
  file: springboot.log
  level:
    root: warn #全部日志级别
    com:
      neo:
        dao: debug #指定目录日志级别
#多数据源配置
datasource:
  test1:
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800 #就是这句话
  test2:
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800 #就是这句话
#变量
commonproperties:
  schemaCrm: crm
  modelMap: {"name":"123"}
redis:
  # Redis数据库索引（默认为0）
  database: 0
  # Redis服务器地址
  host: localhost
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接端口
  password:
  maxTotal: 200
  pool:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: 10000
  # 连接超时时间（毫秒）
  timeout: 0